name: Build plugin
on:
  push:
    branches:
      - master
jobs:
  Build-Plugin:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Setup Java 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build with Gradle and cache
        uses: burrunan/gradle-cache-action@v1
        with:
          arguments: buildPlugin
      - name: Archive jar
        uses: actions/upload-artifact@v2
        with:
          name: intellij-ngx-translate-support
          path: build/libs/*.jar

concurrency:
  group: env-${{ github.head_ref }}
  cancel-in-progress: true
